name: Playwright Tests on all Ubuntu Github Runners
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '10 6 * * 1'
  workflow_dispatch:
jobs:
  e2e-test:
    name: End 2 End Test
    timeout-minutes: 60
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ "ubuntu-24.04", "ubuntu-22.04" ]
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2

      - name: Setup Node
        uses: actions/setup-node@v4.4.0
        with:
          node-version: lts/*

      - name: Start FusionAuth
        uses: fusionauth/fusionauth-github-action@v1
        with:
          FUSIONAUTH_APP_KICKSTART_DIRECTORY_PATH: kickstart

      - name: Install Application
        run: npm i --prefix "./complete-application/"

      - name: Build Application
        run: npm run build --prefix "./complete-application/"

      - name: Run Application
        run: npm start --prefix "./complete-application/" &

      - name: Run Playwright Quickstart E2E Test
        uses: sonderformat-llc/run-quickstart-e2e-test@v0.2.5
        with:
          FUSIONAUTH_URL: 'http://localhost:9011'
          QUICKSTART_URL: 'http://localhost:3000'
          ARTIFACT_PREFIX: 'playwright-${{ matrix.os }}'
